In [4]:
import os
import sys

import matplotlib.pyplot as plt
import numpy as np

sys.path.append("../../detr")
import torch
import cv2
from scipy import stats
from PIL import Image
from glob import glob

In [26]:
# image_root = '/home/suqi/dataset/MolScribe/preprocessed'
# image_names = [
#     'indigo_validation_set_examples_0000000.png',
#     'indigo_validation_set_examples_0000001.png',
#     'indigo_validation_set_examples_0000002.png',
#     'indigo_validation_set_examples_0000003.png',
#     'indigo_validation_set_examples_0000004.png',
#     'indigo_validation_set_examples_0000005.png',
#     'indigo_validation_set_examples_0000006.png',
#     'indigo_validation_set_examples_0000007.png',
#     'indigo_validation_set_examples_0000008.png',
#     'indigo_validation_set_examples_0000009.png'
# ]
# 
# for image_name in image_names[1:]:
#     image = Image.open(os.path.join(image_root, image_name)).convert('RGB')
#     stroke = image_stroke_size(np.array(image))
#     print(stroke)
#     plt.imshow(image)
#     plt.show()
# 
#     sizes = np.reshape(sizes, (-1,))
#     plt.hist(sizes, bins=range(1, 10, 1))
#     plt.show()
image = np.ones(shape=(20, 20, 3), dtype=np.uint8) * 255
# image = cv2.line(image, (0, 5), (10, 5), thickness=3, color=(0, 0, 0))
image = cv2.rectangle(image, (3, 3), (18, 18), thickness=4, color=(0, 0, 0))
stroke = image_stroke_size(np.array(image))
print(stroke)
plt.imshow(image)
plt.show()
"""
[[255   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255 255 255 255   0   0]
 [  0   0   0 255 255 255 255 255   0   0]
 [  0   0   0 255 255 255 255 255   0   0]
 [  0   0   0 255 255 255 255 255   0   0]
 [  0   0   0 255 255 255 255 255   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]
"""

[ 0 23 60 27 62 24 31  0 29] [1.38461338 0.26502366 1.53605547 0.0703124  1.6334111  0.21634584
 0.12439886 1.38461338 0.02704323]


ValueError: zero-size array to reduction operation maximum which has no identity

In [5]:
pdf_root = '/home/suqi/dataset/pdf_data'
save_root = '/home/suqi/dataset/pdf_images'
os.makedirs(save_root, exist_ok=True)

pdf_paths = sorted(glob(os.path.join(pdf_root, '**', '*.pdf'), recursive=True))

In [6]:
print(len(pdf_paths))
pdf_names = [path.split('/')[-1] for path in pdf_paths]
print(pdf_names.index("9850-9857.pdf"))

3714
774
